config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :ads
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'ads#index'
end

app/models/ad.rb
class Ad < ApplicationRecord
	validates :title, :desc, :tel, :name, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :name, :email, presence: true
  validates :email, uniqueness: true
  has_secure_password
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :set_ad, only: [:show, :edit, :update, :destroy]
  skip_before_action :authorize, only: [:index, :show, :new, :create] 
	
  # GET /ads
  # GET /ads.json
  def index
    @ads = Ad.all
  end

  # GET /ads/1
  # GET /ads/1.json
  def show
  end

  # GET /ads/new
  def new
    @ad = Ad.new
  end

  # GET /ads/1/edit
  def edit
  end

  # POST /ads
  # POST /ads.json
  def create
    @ad = Ad.new(ad_params)

    respond_to do |format|
      if @ad.save
        format.html { redirect_to @ad, notice: 'Ogłoszenie zostało stworzone.' }
        format.json { render :show, status: :created, location: @ad }
      else
        format.html { render :new }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ads/1
  # PATCH/PUT /ads/1.json
  def update
    respond_to do |format|
      if @ad.update(ad_params)
        format.html { redirect_to @ad, notice: 'Ogłoszenie zostało zaktualizowane.' }
        format.json { render :show, status: :ok, location: @ad }
      else
        format.html { render :edit }
        format.json { render json: @ad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ads/1
  # DELETE /ads/1.json
  def destroy
    @ad.destroy
    respond_to do |format|
      format.html { redirect_to ads_url, notice: 'Ogłoszenie zostało usunięte.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ad
      @ad = Ad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ad_params
      params.require(:ad).permit(:title, :desc, :tel, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authorize
  def authorize
    unless User.find_by(id: session[:user_id])
      redirect_to login_url, notice: "Zaloguj się"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
skip_before_action :authorize
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to admin_url, notice: "Zalogowałeś się poprawnie."
    else
      redirect_to login_url, alert: "Złe hasło lub/i adres e-mail."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to ads_url, notice: "Zostałeś poprawnie wylogowany"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'Użytkownik został poprawnie dodany.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Użytkownik został poprawnie edytowany.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'Użytkownik został skasowany.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
<% end %>    <br /><br /><br /><br /><br /><br />
<h1>Jesteś teraz zalogowany.</h1>
<h2>Możesz teraz edytować i usuwać ogłoszenia na głównej stronie</h2><br /><br /><br /><br />
<%= button_to 'Wyloguj', logout_path, method: :delete %><br /><br />
 <%= yield %>

app/views/ads/_form.html.erb
<%= form_for(ad) do |f| %>
  <% if ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ad.errors.count, "error") %> prohibited this ad from being saved:</h2>

      <ul>
      <% ad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="row control-group">
                            <div class="form-group col-xs-3 col-xs-offset-4  controls">
                                 <%= f.label :title %>
                                 <%= f.text_field :title %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
 <div class="row control-group">
                            <div class="form-group col-xs-3 col-xs-offset-4  controls">
                                  <%= f.label :desc %>
                                <%= f.text_area :desc %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
						 <div class="row control-group">
                            <div class="form-group col-xs-3 col-xs-offset-4  controls">
                                 <%= f.label :tel %>
                                <%= f.number_field :tel %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>
						 <div class="row control-group">
                            <div class="form-group col-xs-3 col-xs-offset-4 controls">
                               <%= f.label :name %>  
    <%= f.text_field :name %>
                                <p class="help-block text-danger"></p>
                            </div>
                        </div>

     <div class="row">
                            <div class="form-group col-xs-6 col-xs-offset-4">
                                    <%= f.submit %>
                            </div>
                        </div>

 
<% end %>

app/views/ads/edit.html.erb
<br /><br /><br /><br />
<section id="contact">
 <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Edycja</h2>
                    <hr class="star-primary">
                </div>
            </div>  
 <div class="row">
                <div class="col-lg-8 col-lg-offset-2">			
<%= render 'form', ad: @ad %>
       </div>  
     </div>
            </div>       
    </section>



<%= link_to 'Show', @ad %> |
<%= link_to 'Back', ads_path %>

app/views/ads/index.html.erb
<p id="notice"><%= notice %></p>
<br /><br /><br /><br />
 <% @ads.order("created_at desc").each do |ad| %>
  <section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2><%= ad.title %></h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 col-lg-offset-2">
                    <p><%= truncate(ad.desc, :length => 200, :omission => '... (czytaj dalej)') %></p>
					
                </div>
                <div class="col-lg-3">
                    <p>Autor: <%= ad.name %></p>
					<p>Telefon: <%= ad.tel %></p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h3><mark>
                        <%= link_to 'Link', ad %> 
						<% if session[:user_id] %> |
						<%= link_to 'Edytuj', edit_ad_path(ad) %> | 
						<% end %>
						<% if session[:user_id] %>
						<%= link_to 'Usuń', ad, method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
                    </mark></h3>
                </div>
            </div>
        </div>
    </section>
<br /> <br />

<% end %>

app/views/ads/new.html.erb
<br /><br /><br /><br /><br />
<div class="containter">
<div class="row"><div class="col-md-4 col-md-offset-4"><h1>Nowe ogłoszenie</h1></div></div></div>
<%= render 'form', ad: @ad %>

<%= link_to 'Back', ads_path %>

app/views/ads/show.html.erb
<p id="notice"><%= notice %></p>
<br /><br /><br /><br />
<section class="success" id="about">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2><%= @ad.title %></h2>
                    <hr class="star-light">
                </div>
            </div>
            <div class="row">
                <div class="col-lg-5 col-lg-offset-2">
                    <p><%= @ad.desc %></p>
					
                </div>
                <div class="col-lg-3">
                    <p>Autor: <%= @ad.name %></p>
					<p>Telefon: <%= @ad.tel %></p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h3><mark>
                        <%= link_to 'Back', ads_path %>
						<% if session[:user_id] %> |
						<%= link_to 'Edytuj', edit_ad_path(@ad) %></mark></h3> 
						<% end %><br />
						<% if session[:user_id] %>
						<%= button_to 'Usuń', @ad, method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
                    
                </div>
            </div>
        </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tablica ogłoszeń</title>
	<%= javascript_include_tag(:defaults) %>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %>
	<link href="http://r91s.webd.pl/rails/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="http://r91s.webd.pl/rails/css/freelancer.min.css" rel="stylesheet">
	<link href="http://r91s.webd.pl/rails/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
	</head>

  <body id="page-top" class="index">
      <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Nawigacja</span> Menu <i class="fa fa-bars"></i>
                </button>
               
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
				
					<li class="page-scroll">
                        <%= link_to 'Ogłoszenia', ads_path  %>
                    </li>
					<li class="page-scroll">
                   <%= link_to 'Dodaj nowe ogłoszenie', new_ad_path %>
                    </li>
                    <li class="page-scroll">
                        <% if !session[:user_id] %>
						<%= link_to 'Zaloguj', login_path  %>
						<% end %>
                    </li>
                    <li class="page-scroll">
                        <% if session[:user_id] %>
          <%= button_to 'Wyloguj', logout_path, method: :delete %>
        <% end %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
  
  

      <div id="container" >
        <% if flash[:notice] %>
          
        <% end %>
        <%= yield %>
      </div>
    <footer class="text-center">
        <div class="footer-above">
            <div class="container">
                <div class="row">
                    <div class="footer-col col-md-4">
                        
                    </div>
                    <div class="footer-col col-md-4">
                        
                    </div>
                    <div class="footer-col col-md-4">
                        <h3>RoR projekt</h3>
                        <p>Robert Szklarczyk</p>
						<p>Łukasz Knopczyk</p>
						<p>Mateusz Żylski</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-below">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        Ruby on Rails Project - UP Kraków 2017
                    </div>
                </div>
            </div>
        </div>
    </footer>
   <!-- jQuery -->
    <script src="http://r91s.webd.pl/rails/vendor/jquery/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="http://r91s.webd.pl/rails/vendor/bootstrap/js/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

    <!-- Contact Form JavaScript -->
    <script src="http://r91s.webd.pl/rails/js/jqBootstrapValidation.js"></script>
    <script src="http://r91s.webd.pl/rails/js/contact_me.js"></script>

    <!-- Theme JavaScript -->
    <script src="http://r91s.webd.pl/rails/js/freelancer.min.js"></script>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>